### ISSUE TITLE
Aliasing issuns and non-standard conformance in Node union

### ISSUE THREAD

**Issue by pizzard** [jlblancoc/nanoflann#10]
https://github.com/jlblancoc/nanoflann/blob/master/include/nanoflann.hpp#L778

There are some problems with this code:
Unnamed structs in unions are not allowed in C++98. gcc doesn't know that, clang does.
There is also a very bad aliasing issue, because IndexType might not have the same size as the other struct, in my case 4 bytes off.

**Comment by jlblancoc** [comment]
We will fix the unnamed structs in union, thanks!

On aliasing, from the comment in the code: `so both data fields are never used simultaneously`
==> we actually don't care about the two union members having different sizes or not being aligned because only one of them will be ever accessed. 
I admit it is an "ugly" trick but it saves some memory and avoids the runtime cost of other alternatives like polymorphism, etc. In trees with millions of nodes, it is worth bearing that little ugly part ;-)

**Comment by pranjal-rai** [comment]
I have created a pull request. It is showing error "The Travis CI build failed" on some test. 
You can check it in the following link https://travis-ci.org/jlblancoc/nanoflann/builds/114402820.
