### ISSUE TITLE
Does the nanoflann support EPS?

### ISSUE THREAD

**Issue by supermice** [jlblancoc/nanoflann#103]
It's mentioned in the readme.md that there would be no support for approximate NN. But after I look into the code, it seems  approximate NN is supported already. Code below is in the searchLevel() function. It shows the usage of the parameter of EPS.

` if (mindistsq * epsError <= result_set.worstDist()) `

**Comment by jlblancoc** [comment]
Hi, 

Good point. It's confusing because I've tried (until now) to strictly keep the same API interface than the original FLANN project, so here we have that EPS parameter in the SearchParams which always defaults to zero. 

But even if you set it to something different, you'll get **more** calls to `ResultSet::addPoint()`, but with the ResultSets available in this repo, only the closest result will remain after all... so it would be a waste of time, actually!

I'm longing to, someday, head towards a nanoflann-2.0 with a totally cleaned up API! ;-)
