### ISSUE TITLE
L2 distance of points/vector of angular/rotational values

### ISSUE THREAD

**Issue by kleibrandt** [jlblancoc/nanoflann#109]
I would like to use nanoflann for radius search and nearest neighbor searches in the joint space of a robotic actuator. 

This means my "points" in the point cloud are vectors of angular values (revolute joints). To compute the correct distance between two points I would like to compute the angular distance per dimension (like the SO2_Adaptor, which ensures that the distance between an angle of 2π and an angle of 0 is zero). Then I would like use the L2-norm on this vector of angular distances. Would I be able to to just use a new adaptor class which overloads the: `evalMetric` and `accum_dist` methods? 
My understanding is that the:
 `accum_dist` returns the squared distance between two points (`a`,`b`) ,
and that:
 `evalMetric` also returns the squared distance but `a` being the pointer to first dim of the point A and `b` the index to the corresponding point B in the indexed cloud. 
Is that correct?

Also it seems that the correct adaptor class must be known at compile time. So I cannot provide an object which provides the `accum_dist` and  `evalMetric` methods? I assume the reason for this are mainly code optimization considerations?

**Comment by jlblancoc** [comment]
Hi @kleibrandt , 

Yes, all your assumptions are correct!

Except, that the fact that evalMetric() returns the *squared* distance is a matter of convention and efficiency, you are free of defining a metric adaptor that returns "regular" distances without problems. Only, that fact should be known by the user when making requests based on a maximum radius and such. 

About the possibility of switching between metrics: I'm afraid it should be done on the user side, since as you said, nanoflann is entirely based on the CRTP at compile time. 

You could define a virtual base class with the request API of your need, then derive a couple of classes from it, making them to *also* derive (or contain as members) different instances of nanoflann indices with different metrics, and using safe pointers to keep a reference to the index, e.g. `std::unique_ptr<IndexBase> = std::dynamic_pointer_cast<std::make_shared<IndexForMetric1>>();`
