### ISSUE TITLE
default constructor is missing

### ISSUE THREAD

**Issue by jingpengw** [jlblancoc/nanoflann#114]
the index constructed can not do copy assignment. we need default constructor for it?

I am using the index as a class private variable, but I can not copy the index from another class instance. I need to construct it from scratch, which might be inefficient.

references:
https://en.cppreference.com/w/cpp/language/default_constructor
https://en.cppreference.com/w/cpp/language/copy_assignment

**Comment by jlblancoc** [comment]
Hi @jingpengw !
Sorry for the late reply...

I have replicated your problem, and trying to get a fix for it stumbled into the reasons default ctor and copy ctor were explicitly marked as a deleted functions:
1) the data source adaptor is kept as a const reference. It could be converted into a std::reference or into a pointer, but code would be more error prone then...
2) index data is also kept as a dynamic object (dynamic memory), so the index object now owns the memory in a clear way. Allowing making copies would imply the extra work of dealing with swallow vs deep copies, etc. Using shared_ptr or unique_ptr are neither good solutions, IMO. 

So, my advise is for you is really simple: instead of keeping nanoflann indices around, keep std::shared_ptr to them! Then they will be trivially copiable, the shared_ptr can be default constructed, copy cost would be virtually zero, etc. ;-)
