### ISSUE TITLE
Decide whether all points within a given radius have been found

### ISSUE THREAD

**Issue by szhorvat** [jlblancoc/nanoflann#185]
I am looking to enumerate points around a given centre and process them one by one. At each step of the enumeration, I need to decide whether all points within a radius $r$ of the centre have been found. $r$ may change in each step, and may decrease in successive steps.

Is there a way to do this with nanoflann?

I see that I can use `findNeighbors()` with a callback function, defined through its `result` argument. I am looking at `KNNResultSet` as a reference while implementing an appropriate class for `result`. I assume that what I want has to do with the `worstDist()` member function, but it is not entirely clear what its purpose is, and how its return value is used by `findNeighbors()`. Can you please clarify this @jlblancoc ?

**Comment by jlblancoc** [comment]
Hi, 

The key is to implement a custom `ResultSet` class, as you correctly guessed, but using the return value from this method to stop the search:

https://github.com/jlblancoc/nanoflann/blob/bd3657fd7e67e499dbc1b028ee454a94af47db15/include/nanoflann.hpp#L194-L199


In your case the potential maximum distance is unbounded, so do as in the `KNNResultSet` class and return `worstDist() -> std::numeric_limits<DistanceType>::max()`.

**Comment by szhorvat** [comment]
Thanks for the response. Let me clarify my question.

I do understand how to use `addPoint()`, and I do have a result class implemented that is modelled on `RadiusResultSet` and searches up to a given distance, fixed at the beginning.

However, as I keep processing each new point in `addPoint()`, I am able to determine that it is sufficient to only search up to a smaller radius $r$.  How can I indicate that the search can terminate once all points up to $r$ were found?

Note that each new point that I process in `addPoint()` potentially allows me to decrease the value of $r$. It is changing dynamically.

Do I simply return this $r$ value from `worstDist()`?  Will that terminate the search appropriately?  It is unclear to me what `worstDist()` should return, and what it's effect is.

I know that I can return `false` from `addPoint()` to indicate that the search must terminate. But my termination condition is that all points up to $r$ have already been found. I don't know how to test for this condition from `addPoint()`.

**Comment by jlblancoc** [comment]
Ok, after the clarification I got your (fair) point. The answer is "yes, but...": 
- Returning the (possibly dynamic) maximum desired radius in `worstDist()` will make the recursive search to stop even considering other tree branches if the expected cost is larger than that value.
- But, note that if you change `worstDist()` *while* nanoflann is iterating over a leaf node, it will not immediately stop sending you new calls to `addPoint()`, since it caches the `worstDist()` value when the search reaches such leaf node. That's because points in leafs are not sorted, so there are no guarantees that you will receive the points within one particular leaf in any convenient order.
