### ISSUE TITLE
Stop Search immediatly

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [jlblancoc/nanoflann#20]
Hello,

I'm using radius search with a custom callback. I would like to know if there is a way to stop the search right immediately. (or maybe a link to the documentation of the ResultSet interface)

Thank you very much for your help

**Comment by benadler** [comment]
I also would like to stop the search once a suitable point has been found. I see two ways:

* have ..ResultSet::addPoint(....) return a boolean, indicating whether more points should be searched for. So once addPoints() returns false, the search is stopped. Since addPoint() is called from the recursing searchLevel(), searchLevel() would now also have to return a boolean, or set a "bool& continueSearching" in its parameter-list to false. Sounds like a lot of return-value checking, not sure how much it would slow things down.

* have ...ResultSet::addPoint() call KDTreeSingleIndexAdaptor::stopSearch() when it has enough, and searchLevel() checks that boolean regularly.

@jlblancoc what do you think? Would you accept a pullrequest for something along these lines?

**Comment by jlblancoc** [comment]
@benadler I like the first approach... sure, propose a PR and I'll review it for merging!

Be sure of updating *all* ResultSet's, checking that compilation of examples doesn't break, etc. 

Thanks!

**Comment by pranjal-rai** [comment]
@jlblancoc I guess this can be closed as it was [merged](https://github.com/jlblancoc/nanoflann/pull/40).

**Comment by jlblancoc** [comment]
Right! Thanks
