### ISSUE TITLE
rknnSearch input arg radius or radius squared?

### ISSUE THREAD

**Issue by versatran01** [jlblancoc/nanoflann#239]
Hi, in this line https://github.com/jlblancoc/nanoflann/blob/923c2ac16a955317054c296d298425d33c0cb9de/include/nanoflann.hpp#L1771

The input is named `radius`, but in the `RKNNResultSet`, what it expects is `maximumSearchDistanceSquared`. Is this the intended behavior?

**Comment by jlblancoc** [comment]
The truth is that they are always "distances", but it's up to the specific metric class whether distances are internally interpreted (and measured) as squared or not. 
Many parts of the **generic** API mention "squared" because most people use L2, which follows the squared-distances convention for efficiency, but you might have spotted one API entry that just mentions "generic distance"... 

I know it's confusing, but the general practical rule is: if you use L2 metric, **all distances (inputs or output) are squared**.
