### ISSUE TITLE
E: Unable to locate package libnanoflann-dev

### ISSUE THREAD

**Issue by dqj5182** [jlblancoc/nanoflann#241]
How can I solve this error?

**Comment by jlblancoc** [comment]
Check out the existing nanoflann packages for each Ubuntu distribution [here](https://packages.ubuntu.com/jammy/libnanoflann-dev). May be you are running an older Ubuntu distribution? 

In that case, since nanoflann is source-only, you should be able to manually download and install the .deb file from any of the mirrors in: https://packages.ubuntu.com/noble/all/libnanoflann-dev/download
