### ISSUE TITLE
Build problem for kdtree

### ISSUE THREAD

**Issue by LuanTran07** [jlblancoc/nanoflann#53]
When I try to build this project by
```
cmake ..
make -j4
```

The following error message show up:
```
/home/username/Downloads/nanoflann/3rdparty/libkdtree/kdtree++/kdtree.hpp: In instantiation of ‘std::ostream& KDTree::operator<<(std::ostream&, const KDTree::KDTree<3ul, triplet, std::pointer_to_binary_function<triplet, long unsigned int, double> >&)’:
/home/username/Downloads/nanoflann/3rdparty/libkdtree/examples/test_kdtree.cpp:197:16:   required from here
/home/username/Downloads/nanoflann/3rdparty/libkdtree/kdtree++/kdtree.hpp:1207:28: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘const KDTree::_Node_base’)
       o << "meta node:   " << tree._M_header << std::endl;
```
Did any met same problem, or could helping me to solve this building issue?

**Comment by pranjal-rai** [comment]
The issue is with a third party library. In case if you do not need the benchmarking tool in nanoflann you can switch it off by changing the flag [`BUILD_BENCHMARKS`](https://github.com/jlblancoc/nanoflann/blob/master/CMakeLists.txt#L75). If you switch off this flag, nanoflann will build without any issue.

**Comment by jlblancoc** [comment]
Thanks @pranjal-rai for answering this one!

I've disabled by default the compilation of benchmarks to avoid problems from thirdparty libraries for users who are just interested in using nanoflann.
